language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install --prefer-source --no-interaction --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script:
  phpunit --coverage-text --coverage-clover=coverage.clover
